name: Main Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false

      - name: Install Dependencies
        run: |
          poetry install --with dev

      - name: Run Tests
        env:
          CDOGS_API_BASE_URL: ${{ secrets.CDOGS_API_BASE_URL }}
          CDOGS_APP_ID: ${{ secrets.CDOGS_APP_ID }}
          CDOGS_CLIENT_ID: ${{ secrets.CDOGS_CLIENT_ID }}
          CDOGS_CLIENT_SECRET: ${{ secrets.CDOGS_CLIENT_SECRET }}
          CDOGS_LOGIN_PROXY: ${{ secrets.CDOGS_LOGIN_PROXY }}

          CHEFS_API_KEY: ${{ secrets.CHEFS_API_KEY }}
          CHEFS_FORM_ID: ${{ secrets.CHEFS_FORM_ID }}
          CHEFS_TEST_CONFIRMATION_ID: ${{ secrets.CHEFS_TEST_CONFIRMATION_ID }}
          CHEFS_TEST_SUBMISSION_ID: ${{ secrets.CHEFS_TEST_SUBMISSION_ID }}
          DEBUG_EMAIL: ${{ secrets.DEBUG_EMAIL }}
          JIRA_API_URL: ${{ secrets.JIRA_API_URL }}
          JIRA_CLIENT_EMAIL: ${{ secrets.JIRA_CLIENT_EMAIL }}
          JIRA_CLIENT_ID: ${{ secrets.JIRA_CLIENT_ID }}
          JIRA_CLIENT_SECRET: ${{ secrets.JIRA_CLIENT_SECRET }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}

          CHEFS_API_BASE_URL: ${{ vars.CHEFS_API_BASE_URL }}
          FROM_EMAIL: ${{ vars.FROM_EMAIL }}
          JIRA_COMPONENT: ${{ vars.JIRA_COMPONENT }}
          JIRA_PROJECT: ${{ vars.JIRA_PROJECT }}
          JIRA_TEST_FILE_PATH: ${{ vars.JIRA_TEST_FILE_PATH }}
          JIRA_TEST_ISSUE_KEY: ${{ vars.JIRA_TEST_ISSUE_KEY }}
          JIRA_YOUNGER_THAN_MINUTES: ${{ vars.JIRA_YOUNGER_THAN_MINUTES }}
        run: |
          poetry run pytest
